[package]
name = "rwest-io"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.29", optional = true}
wasm-bindgen-futures = { version = "0.4.1", optional = true }
console_error_panic_hook = { version = "0.1", optional = true}
log = "0.4"
console_log = {version ="0.2", features = ["color"], optional = true}
sauron = "0.43"
serde = { version = "1.0", features = ["serde_derive"]}
serde_json = "1.0"
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }

[features]
default = ["wasm"]
wasm = ["wasm-bindgen", "wasm-bindgen-futures", "console_error_panic_hook", "console_log"]