#+TITLE: rwest-io
#+DATE: 2022-07-26
#+AUTHOR: ellis
#+EMAIL: ellis@rwest.io
#+DESCRIPTION: My Website

This project contains the source code for my personal website,
[[https://rwest.io][rwest.io]].

* Overview
My site consists of a few modules hosted by [[https://www.nginx.com/][Nginx]] (=*= denotes
authentication required):

- org :: static html pages
  - generated with [[https://orgmode.org/][Org-mode]]
  - =/= =/blog= =/notes= =/projects= 
- auth :: auth server
  - OAuth2 service
  - supports discord, google, and github
  - =/login= =/auth= =/logout=
- el :: elsrv *
  - HTTP<->UDP proxy to [[https://www.emacswiki.org/emacs/EmacsLisp][Emacs Lisp]] shell
  - =/el=
- status :: status server
  - =/status=

These are the frontend components. We also have a few backend
components, most notably a Postgres DB service and a running Emacs
session.

#+begin_src artist
                                      ORG    = static html pages
                                      AUTH   = auth server  
                                      EL     = elsrv proxy     	 
                                      STATUS = status server 




  +----------+		      		       		
  |          |		      		       		
  |          |  	      			       		
  |          |  +----------------+               	      	
  |          |  |                |   +----------------+	
  |          |  |    ORG         |   |                |	
  |          |  |                |   |                |  	
  |          |  +----------------+   |   	   DB       |
  |          |  |                |   |                |
  |          |  |    AUTH        |   |                |
  |  NGINX   |  |                |   +----------------+
  |          |  +----------------+               	      
  |          |  |                |   +----------------+
  |          |  |    EL          |   |                |
  |          |  |                |   |                |
  |          |  +----------------+   |     EMACS      |
  |          |  |                |   |                |
  |          |  |    STATUS      |   |                |
  |          |  |                |   +----------------+
  |          |  +----------------+          
  |          |
  |          |
  |          |
  +----------+
#+end_src
** Modules
- there are two types of modules worth mentioning here: static
  (org) and dynamic (auth el status).
  - *Static* modules do not interact with the backend and are just
    'compiled' files which can then be served by any web server.
  - *Dynamic* modules are applications which send and receive
    information on specified sockets. They interact with backend
    components and need too be reverse proxied when used in a web
    server like Nginx.
    - binaries shipped with dynamic modules run as separate services.
    - configured at runtime
    - flexible routing - host each service across LAN/WAN
*** org
*** auth
- authsrv
*** el
- elsrv
- elsrv.el
*** status
- statsrv
* resources
- [[https://gitlab.com/OlMon/org-themes/-/tree/master/][org themes]]
- [[https://www.postgresql.org/docs/current/index.html][postgres docs]]
- [[http://nginx.org/en/docs/][nginx docs]]
- [[https://github.com/tokio-rs/axum][axum]]
- [[https://github.com/ryanpig/wasm_terminal_2048][wasm_terminal_2048]]
- [[https://rustwasm.github.io/docs/book/][Rust and WebAssembly]]
- [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Byte-Packing.html][elisp -- Byte Packing]]
- [[https://www.gnu.org/software/emacs/manual/html_node/elisp/Processes.html][elisp -- Processes]]
