[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
client = { path = "../client", default-features = false }
sauron = { version = "0.43", default-features = false }
tokio = { version = "1.16", features = ["full"] }
serde_json = "1.0"